[package]
name = "mod_handler"
version = "1.0.0"
edition = "2021"
authors = ["Jakkoble <business@jakkoble.de>"]
description = "A simple handler for Minecraft Mods"

[dependencies]
crossterm = "0.27.0"
